# Generated by Django 3.0.5 on 2022-07-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_donor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='Email',
            field=models.EmailField(default=0, max_length=50),
        ),
    ]
