# Generated by Django 3.0.5 on 2022-07-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Email',
            field=models.EmailField(default=0, max_length=250),
        ),
    ]
