# Generated by Django 3.0.5 on 2022-07-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20220709_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
