# Generated by Django 3.0.5 on 2022-06-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='mobile',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
